# Generated by Django 3.2.4 on 2021-12-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xMin', models.FloatField(default=0)),
                ('yMin', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('label', models.CharField(default='', max_length=256)),
                ('pic_num', models.IntegerField(default=0)),
                ('mission', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='mission_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(default='', max_length=256)),
                ('mission', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='missions',
            fields=[
                ('description', models.CharField(default='', max_length=256)),
                ('state', models.CharField(choices=[('0', '未完成'), ('1', '已完成'), ('2', '审核中')], default='未完成', max_length=20, verbose_name='任务状态')),
                ('puber', models.CharField(default='', max_length=256)),
                ('recieve', models.CharField(default='', max_length=256)),
                ('mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_num', models.IntegerField(default=0)),
                ('pic_tat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pic_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(default='', max_length=256)),
                ('puber', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
