# Generated by Django 3.2.4 on 2021-11-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.FileField(default='avatars/default.jpg', upload_to='avatars/')),
            ],
        ),
    ]
