# Generated by Django 3.2.4 on 2021-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20211207_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='mission_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
