# Generated by Django 3.2.4 on 2021-12-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_missions_mission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='mission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urls',
            name='mission',
            field=models.IntegerField(default=0),
        ),
    ]
